# <center><u>Numpy</u></center>

## 1. Variable Declarartion

In [1]:
# Import numpy using alias np

import numpy as np

In [4]:
# create a numpy array 'a' with elements 1,2,3
# create a two dimensional array 'b' with elements(1,2,3) and (4,5,6)

a = np.array([1,2,3])
b = np.array([[1,2,3],[1,3,3]])

In [5]:
# print the values of a and b
print(a)
print(b)


[1 2 3]
[[1 2 3]
 [1 3 3]]


Print shape of both a and b

In [6]:
# your code here
print(a.shape)
print(b.shape)


(3,)
(2, 3)


Print the data types of a and b

In [7]:
print(type(a))
print(type(b))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## 2. Add, remove elements and Memory Sharing


Declare x = np.array([ 5,10, 20, 12, 3])

In [8]:
# declare x 
x = np.array([ 5,10, 20, 12, 3])

Add a new element 1 at the end of x

In [9]:
# your code here
 
x = np.append(x,1)
print(x) # check if 1 is added 

[ 5 10 20 12  3  1]


Delete the second element of x 


In [10]:
# your code here 

x = np.delete(x,1)
print(x) # check if the second element has been deleted

[ 5 20 12  3  1]


Set y = x


In [11]:
y = x


Set the first element y =  1


In [12]:
# set first element of y to be 1
y[0] = 1

print(y)

[ 1 20 12  3  1]


Print x and y



In [15]:
print(x)
print(y)



[ 1 20 12  3  1]
[ 1 20 12  3  1]


<b>you modified y, OMG!! but why x is also affected? Just give a try to answer this quest below </b>

### X is set to y when y changed automatically x gets changed

Set z = np.copy(x)


In [17]:
z = np.copy(x) #your code here


Set the first element of z as 100


In [18]:
z[0] = 100


print x and z to see if there is any change in x.

In [19]:
print(x)
print(z)


[ 1 20 12  3  1]
[100  20  12   3   1]


<b>Hey the above output seems so interesting!!. When used copy function the changes did not affect on x. Can you Guess why ?<b>

### The above z is copied from x so when z cahnges x doesnt changed.

## 4. Using various Numpy Functions.



Create a numpy array containing numbers from 1 to 12

In [20]:
#your code here 

print(x)

[ 1 20 12  3  1]


Create a numpy array containing even numbers between 1 to 20




In [27]:
x = np.arange(2,21,2)

print(x)

[ 2  4  6  8 10 12 14 16 18 20]


Create an array of 2 rows and 2 columns containing all zeros.




In [28]:
# your code here
x = np.zeros([2,2])
print(x)

[[0. 0.]
 [0. 0.]]


Create a matrix containing 3 rows and 2 columns where all the values are 1.




In [30]:
# your code here 
x = np.ones([3,2])
print(x)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


Create a matrix of size 5x5 where all are diagonal elements are 1, rest being 0.

In [31]:
# your code here
x = np.identity(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Create a matrix of size 4x2 where all the elements are 4




In [33]:
# your code here
x = np.full((4,2),4)
print(x)

[[4 4]
 [4 4]
 [4 4]
 [4 4]]


Create a matrix where diagonal elements are [1 , 2, 3, 4, 5] and rest are zero




In [34]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Create a matrix of size 3x3 which contains random numbers from 0 to 1.




In [35]:
# your code here
x =  np.random.random((3, 3))
print(x)

[[0.5700114  0.02939235 0.53459485]
 [0.98916965 0.07522426 0.29987311]
 [0.26777531 0.39243507 0.91503152]]


Create a numpy array of shape (50,) such that it contains evenly spaced numbers, from 1 to 20.

In [36]:
# your code here
x = np.linspace(1, 20, num=50)

print(x)

[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]


## 5. Reshaping


Use np.arange to create  a numpy array with values between 0 to 23

In [40]:
# your code here

a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [41]:
# print the shape of a
a.shape

(24,)

Using a suitable method, reshape a to have a dimension of (3,8). Print b and its shape


In [42]:
a = a.reshape(3,8)

print(a.shape)
print(a)


(3, 8)
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


Create another numpy array c  = a.reshape(2,-1)

In [43]:
c = a.reshape(2,-1)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [44]:
print(c)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


Print the shape of c.

In [45]:
# your code here
c.shape

(2, 12)

<b>Hey check above, what role -1 has played in reshape function. Don't worry</b>
<b> ok let me tell you this fun fact</b>

When using a -1, the dimension corresponding to the -1 will be the product of the dimensions of the original array divided by the product of the dimensions given to reshape so as to maintain the same number of elements

________

## 6. Accessing numpy arrays




### Create an array, a = np.array([2,4,6,8,10,12,14,16])




In [46]:
# code here

a = np.array([2,4,6,8,10,12,14,16])

In [47]:
# print a

a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

<b>Using indexing and slicing, select the following mentioned subsets - </b>

In [48]:
# [4]
a[1]


4

In [49]:
#[4, 8, 12]

a[1:6:2]

array([ 4,  8, 12])

In [50]:
# [10, 12, 14, 16]

a[-4:]

array([10, 12, 14, 16])

In [51]:
# [14, 16]

a[-2:]

array([14, 16])

In [52]:
# [2, 6, 10, 14]

a[0:8:2]

array([ 2,  6, 10, 14])

## 7. Transposing



Create an array a = np.array([ [1, 2, 3], [4, 5, 6], [7,8,9], [10,11,12] ] )


In [53]:
# your code here
a = np.array([ [1, 2, 3], [4, 5, 6], [7,8,9], [10,11,12] ] )

What is the shape of a?

In [54]:
# your code here
a.shape

(4, 3)

### Create another array b which is transpose of a

In [55]:
# your code here
b = a.T

Print b and its shape

In [56]:
# your code here
print(b.shape)
print(b)

(3, 4)
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


## 8. Mathematical Operations



### Complete the following tasks given in comment using numpy function.

In [57]:
# complete your tasks here

# Create an array, a = np.arange(10) and print a
a = np.arange(10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


In [58]:
# Find sin value of a
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [59]:
# Find cos value a
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [60]:
# Find exponential of all the values in a.
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [62]:
# Find the sum of all the values in a.
np.sum(a)

45

In [63]:
# Find the median value in a.
np.median(a)

4.5

In [64]:
#Find the max value of a
np.max(a)

9

In [65]:
#Find the min value of a
np.min(a)

0

In [69]:
# Find the index of the maximum element in a
x = np.where(a == np.max(a))
x[0][0]

9

## 9. Hstack and vstack



Create a = np.array( [ [1, 2, 3], [ 4, 5, 6], [7 ,8, 9] ]) and print a.

In [70]:
# your code here
a = np.array( [ [1, 2, 3], [ 4, 5, 6], [7 ,8, 9] ]) 


print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Create b = np.array( [ [10, 11, 12] , [13,14,15], [16, 17, 18] ]) and print b


In [71]:
# your code here
b = np.array( [ [10, 11, 12] , [13,14,15], [16, 17, 18] ])

print(b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


Create a new array c stacking a and b horizontally, print the values and shape of this array.

In [74]:
# your code here
c = np.hstack([a,b])

print(c)
print(c.shape)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
(3, 6)


Create a new array d stacking a and b vertically, print the values and shape of this array.

In [75]:
# your code here
d = np.vstack([a,b])

print(d)
print(d.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
(6, 3)


In [76]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

What is the average value of the second column (to two decimal places)

In [77]:
#your code
random_integers.mean(axis=0)[1]

214895.8

What is the average value of the first 5 rows of the third and fourth columns?

In [78]:
#your code
np.mean(random_integers[:5,2:4])

286058.5

Write a NumPy program to sort an given array by the nth column.

In [79]:
a = np.array([[10, 40],[30, 20]])

In [82]:
np.sort(a)

array([[10, 40],
       [20, 30]])

In [86]:
#create a array like below output
arr = np.array([['James' ,'5', '48.5'],
 ['Nail', '6' ,'52.5'],
 ['Paul', '5' ,'42.1'],
 ['Pit' ,'5' ,'40.11']]
)
arr

array([['James', '5', '48.5'],
       ['Nail', '6', '52.5'],
       ['Paul', '5', '42.1'],
       ['Pit', '5', '40.11']], dtype='<U5')

In [87]:
# write your code here to sort by height of the student as below output
sorted(arr, key=lambda x: x[2])

[array(['Pit', '5', '40.11'], dtype='<U5'),
 array(['Paul', '5', '42.1'], dtype='<U5'),
 array(['James', '5', '48.5'], dtype='<U5'),
 array(['Nail', '6', '52.5'], dtype='<U5')]

In [11]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])

In [12]:
#write you code here


(array([0, 3, 4]),)


Matrix Generation with one particular value

In [88]:
#write you code here
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

Array Generation by repeatition of a small array across each dimension

In [89]:
a = np.array([[1,2,3],
              [4,5,6]])

In [91]:
#your code

print(np.tile(a,5))

[[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]]


In [104]:
#write code to generate following code
out = []
for i in k:
    if i%2 == 0:
        out.append(i)
        out.append(-1)
        
print(out)

[0, -1, 2, -1, 4, -1, 6, -1, 8, -1]
